import sqlite3

conn = sqlite3.connect('food.db')
c = conn.cursor()

# create table
c.execute('''CREATE TABLE food
             (id INTEGER PRIMARY KEY AUTOINCREMENT,
             product_name TEXT,
             brands TEXT,
             brands_tags TEXT,
             categories TEXT,
             categories_tags TEXT,
             categories_en TEXT,
             origins TEXT,
             origins_tags TEXT,
             origins_en TEXT,
             countries TEXT,
             countries_tags TEXT,
             countries_en TEXT,
             image_url TEXT,
             image_ingredients_url TEXT,
             image_nutrition_url TEXT,
             energy_kcal_100g REAL,
             fat_100g REAL,
             saturated_fat_100g REAL,
             unsaturated_fat_100g REAL,
             omega_3_fat_100g REAL,
             omega_6_fat_100g REAL,
             omega_9_fat_100g REAL,
             trans_fat_100g REAL,
             cholesterol_100g REAL,
             carbohydrates_100g REAL,
             sugars_100g REAL,
             sucrose_100g REAL,
             glucose_100g REAL,
             fructose_100g REAL,
             lactose_100g REAL,
             maltose_100g REAL,
             fiber_100g REAL,
             soluble_fiber_100g REAL,
             insoluble_fiber_100g REAL,
             proteins_100g REAL,
             salt_100g REAL,
             added_salt_100g REAL,
             sodium_100g REAL,
             alcohol_100g REAL,
             vitamin_a_100g REAL,
             beta_carotene_100g REAL,
             vitamin_d_100g REAL,
             vitamin_e_100g REAL,
             vitamin_k_100g REAL,
             vitamin_c_100g REAL,
             vitamin_b1_100g REAL,
             vitamin_b2_100g REAL,
             vitamin_pp_100g REAL,
             vitamin_b6_100g REAL,
             vitamin_b9_100g REAL,
             vitamin_b12_100g REAL,
             bicarbonate_100g REAL,
             potassium_100g REAL,
             chloride_100g REAL,
             calcium_100g REAL,
             phosphorus_100g REAL,
             iron_100g REAL,
             magnesium_100g REAL,
             zinc_100g REAL,
             copper_100g REAL,
             manganese_100g REAL,
             fluoride_100g REAL,
             selenium_100g REAL,
             chromium_100g REAL,
             molybdenum_100g REAL,
             iodine_100g REAL,
             caffeine_100g REAL,
             carbon_footprint_100g REAL,
             carbon_footprint_from_meat_or_fish_100g REAL,
             cocoa_100g REAL)''')

# commit changes and close connection
conn.commit()
conn.close()

